version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-apps/webChatApp
hooks:
# Install:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
# ValidateService:
